[workspace]
members = [
    "lib/grammers-client",
    "lib/grammers-crypto",
    "lib/grammers-mtproto",
    "lib/grammers-mtsender",
    "lib/grammers-tl-parser",
    "lib/grammers-tl-types"
]

[patch.crates-io]
grammers-tl-parser = { path = "lib/grammers-tl-parser" }
