[package]
name = "scrape-docs"
version = "0.1.0"
authors = ["Lonami Exo <totufals@hotmail.com>"]
edition = "2018"

[dependencies]
html5ever = "0.25.1"
reqwest = "0.10.10"
tokio = { version = "0.2", features = ["full"] }
string_cache = "0.8.1"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
futures = "0.3.8"
